In [3]:
import numpy as np

In [5]:
# Lista de Python vs array de numpy
lista = [1, 2, 3, 4, 5]
array = np.array([1, 2, 3, 4, 5])

print(type(lista))
print(type(array))

# Operacion sobre lista - Se necesita loop
lista_doble = [x * 2 for x in lista]

# Operacion sobre array - Es directo
array_doble = array * 2

print(lista_doble)
print(array_doble)

<class 'list'>
<class 'numpy.ndarray'>
[2, 4, 6, 8, 10]
[ 2  4  6  8 10]


In [7]:
# Array 2D — filas y columnas
matriz = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(matriz)
print("Shape:", matriz.shape)
print("Dimensiones", matriz.ndim)

# Acceder a elementos
print("Fila 0:", matriz[0])
print("Elemento [1, 2]:", matriz[1, 2])
print("Columna 1:", matriz[:, 1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Dimensiones 2
Fila 0: [1 2 3]
Elemento [1, 2]: 6
Columna 1: [2 5 8]


In [8]:
# Practica accediendo a elementos
print(matriz[2, 0])    # ¿qué debería dar?
print(matriz[0, :])    # ¿qué debería dar?
print(matriz[:, 2])    # ¿qué debería dar?
print(matriz[1, :])    # ¿qué debería dar?

7
[1 2 3]
[3 6 9]
[4 5 6]


In [10]:
# Operaciones estadísticas sobre arrays
datos = np.array([15000, 8000, 20000, 12000, 9500, 18000, 15000, 11000, 9000, 22000])

print("Media:", np.mean(datos))
print("Mediana:", np.median(datos))
print("Std:", np.std(datos))
print("Sum:", np.sum(datos))

# Operaciones sobre matrices — por eje
matriz = np.array([
    [15000, 8000, 20000],
    [12000, 9500, 18000],
    [15000, 11000, 9000]
])

print("Suma por columna:", np.sum(matriz, axis=0))
print("Suma por fila", np.sum(matriz, axis=1))

Media: 13950.0
Mediana: 13500.0
Std: 4606.788469204984
Sum: 139500
Suma por columna: [42000 28500 47000]
Suma por fila [43000 39500 35000]


In [11]:
datos = np.array([15000, 8000, 20000, 12000, 9500, 18000, 15000, 11000, 9000, 22000])

#Crear una mascara booleana
mascara = datos > 13000
print("Mascara:", mascara)

#Aplicar la mascara
mayores = datos[mascara]
print("Mayores a 13000:", mayores)

#E n una linea
print("En una linea:", datos[datos > 13000])

Mascara: [ True False  True False False  True  True False False  True]
Mayores a 13000: [15000 20000 18000 15000 22000]
En una linea: [15000 20000 18000 15000 22000]
